development:
  adapter: mysql2
  database: unclenagyshouse_dev
  username: root
  password:
  host: 127.0.0.1

test:
  adapter: mysql2
  database: unclenagyshouse_test
  username: root
  password:
  host: 127.0.0.1

production:
  adapter: mysql2
  database: unclenagyshouse_dev
  username: root
  password:
  host: 127.0.0.1
